### PR TITLE
draw symbol [Symbol] colorrange .hue.

### PR DESCRIPTION
**Pull request by techfips**
added functionality to use z-column as color range from given hue to white (extends existing functionality provided by "gray level z" to arbitrary hues).

### CODE REVIEW

**Comment by dankelley** [comment]
This looks good but I will likely not merge it until next week -- I'm on a deadline for something.  Thanks!! Dan.

**Comment by techfips** [comment]
Hope you made the deadline, just pinging.

**Comment by dankelley** [comment]
Thanks for the ping, because I plain forgot.

**Comment by dankelley** [comment]
I wrote a little bit into `gri.cmd-skel` to describe this (see commit 844358e2dbd999b34364a037f5809f77dbbc7c1f).

Please note that I attributed you as the author of that bit of code. I used your github user name. Is that OK?  I figure I haven't given away any confidences since the info on the pull request is public anyway, and so I attributed without asking.  I hope that's ok ... basically, it's been a long day and I forgot to ask first.  In fact, I would prefer to name you with your real name, or initials. But I would never do that without specific permission. Please send me a private email (dan DOT kelley AT dal DOT ca) to let me know if that's ok. Whatever you prefer is fine ... I can also remove the attribution to your github name, if you wish.

Also, if my explanation is bad, please make another pull request.  All I did was to say a few words on the idea, and give the formula ... for users with programming experience, the actual formula is perhaps more useful than artfully constructed descriptions.

Thanks again!!  It's been a long time since I made a change to gri code ... I've moved on to R for all my graphics and work.

**Pull request merged**
